# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "JPEG {codes}"
description: > # this means to ignore newlines until "email:"
   Códigos azarosos en múltiples lenguajes, JavaScript, Ruby, C, Python. Bienvenidos aquellos que quieran aprender.

email: jpescalonag@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"
fbimage: "/assets/images/df_logo.jpg"
name: 'Juan Pablo Escalona G.'
author: 'Juan Pablo Escalona G.'
author_image: "/assets/images/author.jpg"

gems: [jekyll-paginate]
paginate:	5

url: "http://mammut.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jpescalonag
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mammut
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
